import type { SteamClient } from '../types';
import { App } from '../types/Global/App';
import { AppAchievementProgressCache } from '../types/Global/AppAchievementProgressCache';
import { AppDetailsStore } from '../types/Global/AppDetailsStore';
import { GameRecordingStore } from '../types/Global/GameRecordingStore';
import { PopupManager } from '../types/Global/PopupManager';
import { SteamUIStore } from '../types/Global/SteamUIStore';
import { UrlStore } from '../types/Global/UrlStore';

declare global {
  let App: App;
  let appAchievementProgressCache: AppAchievementProgressCache;
  let appActivityStore: unknown;
  let appDetailsCache: unknown;
  let appDetailsStore: AppDetailsStore;
  let appInfoStore: unknown;
  let appReviewStore: unknown;
  let appSpotlightStore: unknown;
  let appStore: unknown;
  let badgeStore: unknown;
  let ClearBackgroundInterval: unknown;
  let ClearBackgroundTimeout: unknown;
  let ClientConnectionAPI: unknown;
  let cloudStorage: unknown;
  let cloudStorageInternalState: unknown;
  let CLSTAMP: unknown;
  let cm: unknown;
  let collectionStore: unknown;
  let communityStore: unknown;
  let consoleStore: unknown;
  let DebugLogDisable: unknown;
  let DebugLogDisableAll: unknown;
  let DebugLogDisableBacktrace: unknown;
  let DebugLogEnable: unknown;
  let DebugLogEnableAll: unknown;
  let DebugLogEnableBacktrace: unknown;
  let DebugLogNames: unknown;
  let downloadsStore: unknown;
  let dragStore: unknown;
  let EnableSteamConsole: unknown;
  let FocusedAppWindowStore: unknown;
  let FocusNavController: unknown;
  let friendStore: unknown;
  let g_ClanStore: unknown;
  let g_CreatorHomeStore: unknown;
  let g_EventCalendarDevFeatures: unknown;
  let g_EventCalendarMap: unknown;
  let g_EventCalendarTrackingStore: unknown;
  let g_FriendsUIApp: unknown;
  let g_GRS: GameRecordingStore;
  let g_PartnerEventStore: unknown;
  let g_PopupManager: PopupManager;
  let gameReleaseStore: unknown;
  let installFolderStore: unknown;
  let lastScrollTime: unknown;
  let libraryEventStore: unknown;
  let libraryScrollListener: unknown;
  let LocalizationManager: unknown;
  let loginStore: unknown;
  let MainWindowBrowserManager: unknown;
  let multiSelectStore: unknown;
  let NotificationStore: unknown;
  let openDatabase: unknown;
  let overlayStore: unknown;
  let partnerEventStore: unknown;
  let playNextStore: unknown;
  let RemotePlayStore_SteamUI: unknown;
  let ResetNewContentRollup: unknown;
  let screenshotStore: unknown;
  let searchstore: unknown;
  let securitystore: unknown;
  let serverBrowserStore: unknown;
  let SetBackgroundInterval: unknown;
  let SetBackgroundTimeout: unknown;
  let SetHoverPresentation: unknown;
  let settingsStore: unknown;
  let settingsZooStore: unknown;
  let SetVoiceAutoShowVideoStream: unknown;
  let SetVoiceEchoLocalMic: unknown;
  let SetVoiceForceConnectingStatus: unknown;
  let SetVoiceForceReconnectingStatus: unknown;
  let SetVoiceLogDetails: unknown;
  let showcaseStore: unknown;
  let steamAjaxRequest: unknown;
  let SteamClient: SteamClient;
  let SteamUIStore: SteamUIStore;
  let StoreItemCache: unknown;
  let subscriberAgreementStore: unknown;
  let SuspendResumeStore: unknown;
  let SystemDisplayManagerStore: unknown;
  let SystemNetworkStore: unknown;
  let SystemReportStore: unknown;
  let trendingStore: unknown;
  let uiBroadcastWatchStore: unknown;
  let uiStore: unknown;
  let UpdateStore: unknown;
  let urlStore: UrlStore;
  let userProfileStore: unknown;
  let vrAudioSettingsStore: unknown;
  let webpackChunksteamui: unknown;
  let workshopStore: unknown;

  interface Window {
    App: App;
    appAchievementProgressCache: AppAchievementProgressCache;
    appActivityStore: unknown;
    appDetailsCache: unknown;
    appDetailsStore: AppDetailsStore;
    appInfoStore: unknown;
    appReviewStore: unknown;
    appSpotlightStore: unknown;
    appStore: unknown;
    badgeStore: unknown;
    ClearBackgroundInterval: unknown;
    ClearBackgroundTimeout: unknown;
    ClientConnectionAPI: unknown;
    cloudStorage: unknown;
    cloudStorageInternalState: unknown;
    CLSTAMP: unknown;
    cm: unknown;
    collectionStore: unknown;
    communityStore: unknown;
    consoleStore: unknown;
    DebugLogDisable: unknown;
    DebugLogDisableAll: unknown;
    DebugLogDisableBacktrace: unknown;
    DebugLogEnable: unknown;
    DebugLogEnableAll: unknown;
    DebugLogEnableBacktrace: unknown;
    DebugLogNames: unknown;
    downloadsStore: unknown;
    dragStore: unknown;
    EnableSteamConsole: unknown;
    FocusedAppWindowStore: unknown;
    FocusNavController: unknown;
    friendStore: unknown;
    g_ClanStore: unknown;
    g_CreatorHomeStore: unknown;
    g_EventCalendarDevFeatures: unknown;
    g_EventCalendarMap: unknown;
    g_EventCalendarTrackingStore: unknown;
    g_FriendsUIApp: unknown;
    g_GRS: GameRecordingStore;
    g_PartnerEventStore: unknown;
    g_PopupManager: PopupManager;
    gameReleaseStore: unknown;
    installFolderStore: unknown;
    lastScrollTime: unknown;
    libraryEventStore: unknown;
    libraryScrollListener: unknown;
    LocalizationManager: unknown;
    loginStore: unknown;
    MainWindowBrowserManager: unknown;
    multiSelectStore: unknown;
    NotificationStore: unknown;
    openDatabase: unknown;
    overlayStore: unknown;
    partnerEventStore: unknown;
    playNextStore: unknown;
    RemotePlayStore_SteamUI: unknown;
    ResetNewContentRollup: unknown;
    screenshotStore: unknown;
    searchstore: unknown;
    securitystore: unknown;
    serverBrowserStore: unknown;
    SetBackgroundInterval: unknown;
    SetBackgroundTimeout: unknown;
    SetHoverPresentation: unknown;
    settingsStore: unknown;
    settingsZooStore: unknown;
    SetVoiceAutoShowVideoStream: unknown;
    SetVoiceEchoLocalMic: unknown;
    SetVoiceForceConnectingStatus: unknown;
    SetVoiceForceReconnectingStatus: unknown;
    SetVoiceLogDetails: unknown;
    showcaseStore: unknown;
    steamAjaxRequest: unknown;
    SteamClient: SteamClient;
    SteamUIStore: SteamUIStore;
    StoreItemCache: unknown;
    subscriberAgreementStore: unknown;
    SuspendResumeStore: unknown;
    SystemDisplayManagerStore: unknown;
    SystemNetworkStore: unknown;
    SystemReportStore: unknown;
    trendingStore: unknown;
    uiBroadcastWatchStore: unknown;
    uiStore: unknown;
    UpdateStore: unknown;
    urlStore: UrlStore;
    userProfileStore: unknown;
    vrAudioSettingsStore: unknown;
    webpackChunksteamui: unknown;
    workshopStore: unknown;
  }
}
