/* eslint-disable @stylistic/quotes */
import { IMap, InterfaceMap } from '.';

export const SteamClientMaps: InterfaceMap[] = [
  IMap('SteamClient/Apps', 'Apps', /* ts */`SteamClient.Apps`),
  IMap('SteamClient/Auth', 'Auth', /* ts */`SteamClient.Auth`),
  IMap('SteamClient/Auth', 'AuthRefreshInfo', /* ts */`await SteamClient.Auth.GetRefreshInfo()`),
  IMap('SteamClient/Broadcast', 'Broadcast', /* ts */`SteamClient.Broadcast`),
  IMap('SteamClient/Browser', 'Browser', /* ts */`SteamClient.Browser`),
  IMap('SteamClient/ClientNotifications', 'ClientNotifications', /* ts */`SteamClient.ClientNotifications`),
  IMap('SteamClient/Cloud', 'Cloud', /* ts */`SteamClient.Cloud`),
  IMap('SteamClient/CloudStorage', 'CloudStorage', /* ts */`SteamClient.CloudStorage`),
  IMap('SteamClient/CommunityItems', 'CommunityItems', /* ts */`SteamClient.CommunityItems`),
  IMap('SteamClient/Console', 'Console', /* ts */`SteamClient.Console`),
  IMap('SteamClient/Customization', 'Customization', /* ts */`SteamClient.Customization`),
  IMap('SteamClient/Downloads', 'Downloads', /* ts */`SteamClient.Downloads`),
  IMap('SteamClient/FamilySharing', 'FamilySharing', /* ts */`SteamClient.FamilySharing`),
  IMap('SteamClient/Friends', 'Friends', /* ts */`SteamClient.Friends`),
  IMap('SteamClient/FriendSettings', 'FriendSettings', /* ts */`SteamClient.FriendSettings`),
  IMap('SteamClient/GameNotes', 'GameNotes', /* ts */`SteamClient.GameNotes`),
  IMap('SteamClient/GameRecording', 'GameRecording', /* ts */`SteamClient.GameRecording`),
  IMap('SteamClient/GameSessions', 'GameSessions', /* ts */`SteamClient.GameSessions`),
  IMap('SteamClient/index', 'SteamClient', /* ts */`SteamClient`),
  IMap('SteamClient/Input', 'Input', /* ts */`SteamClient.Input`),
  IMap('SteamClient/InstallFolder', 'InstallFolder', /* ts */`SteamClient.InstallFolder`),
  IMap('SteamClient/Installs', 'Installs', /* ts */`SteamClient.Installs`),
  IMap('SteamClient/Internal', 'Internal', /* ts */`SteamClient._internal`),
  IMap('SteamClient/Messaging', 'Messaging', /* ts */`SteamClient.Messaging`),
  IMap('SteamClient/Music', 'Music', /* ts */`SteamClient.Music`),
  IMap('SteamClient/Notifications', 'Notifications', /* ts */`SteamClient.Notifications`),
  IMap('SteamClient/OpenVR', 'OpenVR', /* ts */`SteamClient.OpenVR`),
  IMap('SteamClient/Overlay', 'Overlay', /* ts */`SteamClient.Overlay`),
  IMap('SteamClient/Parental', 'Parental', /* ts */`SteamClient.Parental`),
  IMap('SteamClient/RemotePlay', 'RemotePlay', /* ts */`SteamClient.RemotePlay`),
  IMap('SteamClient/Screenshots', 'Screenshots', /* ts */`SteamClient.Screenshots`),
  IMap('SteamClient/ServerBrowser', 'ServerBrowser', /* ts */`SteamClient.ServerBrowser`),
  IMap('SteamClient/Settings', 'Settings', /* ts */`SteamClient.Settings`),
  IMap('SteamClient/SharedConnection', 'SharedConnection', /* ts */`SteamClient.SharedConnection`),
  IMap('SteamClient/Stats', 'Stats', /* ts */`SteamClient.Stats`),
  IMap('SteamClient/SteamChina', 'SteamChina', /* ts */`SteamClient.SteamChina`),
  IMap('SteamClient/Storage', 'Storage', /* ts */`SteamClient.Storage`),
  IMap('SteamClient/Streaming', 'Streaming', /* ts */`SteamClient.Streaming`),
  IMap('SteamClient/UI', 'UI', /* ts */`SteamClient.UI`),
  IMap('SteamClient/Updates', 'Updates', /* ts */`SteamClient.Updates`),
  IMap('SteamClient/URL', 'URL', /* ts */`SteamClient.URL`),
  IMap('SteamClient/User', 'User', /* ts */`SteamClient.User`),
  IMap('SteamClient/WebChat', 'WebChat', /* ts */`SteamClient.WebChat`),
  IMap('SteamClient/WebUITransport', 'WebUITransport', /* ts */`SteamClient.WebUITransport`),
  IMap('SteamClient/Window', 'Window', /* ts */`SteamClient.Window`),

  IMap('SteamClient/BrowserView/index', 'BrowserView', /* ts */`SteamClient.BrowserView`),
  IMap('SteamClient/BrowserView/BrowserViewPopup', 'BrowserViewPopup', /* ts */`SteamClient.BrowserView.Create()`),

  IMap('SteamClient/System/index', 'System', /* ts */`SteamClient.System`),
  IMap('SteamClient/System/index', 'SystemInfo', /* ts */`await SteamClient.System.GetSystemInfo()`),
  IMap('SteamClient/System/Devkit', 'Devkit', /* ts */`SteamClient.System.Devkit`),
  IMap('SteamClient/System/Display', 'Display', /* ts */`SteamClient.System.Display`),
  IMap('SteamClient/System/Report', 'Report', /* ts */`SteamClient.System.Report`),
  IMap('SteamClient/System/UI', 'UI', /* ts */`SteamClient.System.UI`),
];
