export interface TestObject {
    collection: (Collection | Collection2 | Collection3 | Collection4 | Collection5 | Collection6 | Collection7 | Collection8 | Collection9 | Collection10 | Collection11 | Collection12 | Collection13 | Collection14)[];
  }
  
  export interface Collection {
    BAreCategoriesEqual(e: unknown): unknown;
    BAreSetsEqual(e: unknown, t: unknown): unknown;
    BAreStoreTagsEqual(e: unknown): unknown;
    BHasCustomImages(): boolean;
    BHasNonObservableChange(e: unknown): boolean;
    BHasObservableChange(e: unknown): boolean;
    BHasObservables(): boolean;
    BHasStoreCategory(e: unknown): unknown;
    BHasStoreTag(): unknown /* native code */;
    BIsAppBlocked(): unknown;
    BIsAppInBlockList(): unknown;
    BIsApplicationOrTool(): boolean;
    BIsBorrowed(): unknown;
    BIsDemo(): boolean;
    BIsGameIDEqual(e: unknown): boolean;
    BIsHardware(): boolean;
    BIsLastTimePlayedEqual(e: unknown): boolean;
    BIsModOrShortcut(): unknown;
    BIsMusicAlbum(): boolean;
    BIsNewToLibrary(): unknown;
    BIsOwned(): unknown;
    BIsOwnedByAnotherUser(): unknown;
    BIsPerClientDataEqual(e: unknown): boolean;
    BIsPerClientDataLocal(e: unknown): unknown;
    BIsSelectedClientLocal(): boolean;
    BIsShortcut(): boolean;
    BIsSortAsEqual(e: unknown): boolean;
    BIsSteamDeckVerified(): boolean;
    BIsSteamVR(): unknown;
    BIsUnreleased(): boolean;
    BIsVisibleInMRUList(): boolean;
    BSupportsVR(): unknown;
    ComputeLastPlayedSectionName(e: unknown): unknown;
    GetCanonicalReleaseDate(): unknown;
    GetCanonicalReleaseYear(): unknown;
    GetGameID(): unknown;
    GetLastPlayedSectionName(): unknown;
    GetLastTimePlayed(): unknown;
    GetPerClientData(e: unknown): unknown;
    GetPrimaryAppID(): unknown;
    GetStoreTags(): unknown;
    InitFromProto(e: unknown): void;
    LOG_CHANGE(): unknown /* native code */;
    SetGameID(e: unknown): void;
    SetLastTimePlayed(e: unknown): void;
    SetPerClientData(e: unknown): void;
    SetSortAs(e: unknown): void;
    SetStoreCategories(e: unknown): void;
    SetStoreTags(e: unknown): void;
  
    __cachedLastPlayedSection: undefined;
    __cachedLastPlayedTime: undefined;
    __cachedReleaseYearString: undefined;
    active_beta: undefined;
    album_cover_hash: undefined;
    app_type: number;
    appid: number;
    canonicalAppType: number;
    display_name: string;
    display_status: number;
    gameid: string;
    gamepad_preferred: boolean;
    header_filename: string;
    icon_data: undefined;
    icon_data_format: undefined;
    icon_hash: string;
    installed: undefined;
    is_available_on_current_platform: boolean;
    is_invalid_os_type: undefined;
    library_capsule_filename: string;
    library_id: undefined;
    local_cache_version: number;
    local_per_client_data: Local_per_client_data;
    m_gameid: undefined;
    m_setStoreCategories: Set<number>;
    m_setStoreTags: Set<number>;
    m_ulGameId: undefined;
    mastersub_appid: undefined;
    mastersub_includedwith_logo: undefined;
    metacritic_score: number;
    minutes_playtime_forever: number;
    minutes_playtime_last_two_weeks: number;
    most_available_clientid: string;
    most_available_per_client_data: Local_per_client_data;
    mru_index: undefined;
    number_of_copies: number;
    optional_parent_app_id: undefined;
    owner_account_id: undefined;
    per_client_data: Local_per_client_data[];
    ps4_controller_support: number;
    ps5_controller_support: number;
    review_percentage: number;
    review_percentage_with_bombs: number;
    review_percentage_without_bombs: number;
    review_score: number;
    review_score_with_bombs: number;
    review_score_without_bombs: number;
    rt_custom_image_mtime: undefined;
    rt_last_time_locally_played: undefined;
    rt_last_time_played: number;
    rt_last_time_played_or_installed: number;
    rt_original_release_date: number;
    rt_purchased_time: undefined;
    rt_recent_activity_time: number;
    rt_steam_release_date: number;
    rt_store_asset_mtime: number;
    selected_clientid: string;
    selected_per_client_data: Local_per_client_data;
    shortcut_override_appid: undefined;
    site_license_site_name: undefined;
    size_on_disk: undefined;
    sort_as: string;
    status_percentage: number;
    steam_deck_compat_category: number;
    steam_hw_compat_category_packed: number;
    store_category: number[];
    store_tag: number[];
    subscribed_to: boolean;
    third_party_mod: undefined;
    visible_in_game_list: boolean;
    vr_only: undefined;
    vr_supported: undefined;
    xbox_controller_support: number;
  }
  
  export interface Collection2 {
    BAreCategoriesEqual(e: unknown): unknown;
    BAreSetsEqual(e: unknown, t: unknown): unknown;
    BAreStoreTagsEqual(e: unknown): unknown;
    BHasCustomImages(): boolean;
    BHasNonObservableChange(e: unknown): boolean;
    BHasObservableChange(e: unknown): boolean;
    BHasObservables(): boolean;
    BHasStoreCategory(e: unknown): unknown;
    BHasStoreTag(): unknown /* native code */;
    BIsAppBlocked(): unknown;
    BIsAppInBlockList(): unknown;
    BIsApplicationOrTool(): boolean;
    BIsBorrowed(): unknown;
    BIsDemo(): boolean;
    BIsGameIDEqual(e: unknown): boolean;
    BIsHardware(): boolean;
    BIsLastTimePlayedEqual(e: unknown): boolean;
    BIsModOrShortcut(): unknown;
    BIsMusicAlbum(): boolean;
    BIsNewToLibrary(): unknown;
    BIsOwned(): unknown;
    BIsOwnedByAnotherUser(): unknown;
    BIsPerClientDataEqual(e: unknown): boolean;
    BIsPerClientDataLocal(e: unknown): unknown;
    BIsSelectedClientLocal(): boolean;
    BIsShortcut(): boolean;
    BIsSortAsEqual(e: unknown): boolean;
    BIsSteamDeckVerified(): boolean;
    BIsSteamVR(): unknown;
    BIsUnreleased(): boolean;
    BIsVisibleInMRUList(): boolean;
    BSupportsVR(): unknown;
    ComputeLastPlayedSectionName(e: unknown): unknown;
    GetCanonicalReleaseDate(): unknown;
    GetCanonicalReleaseYear(): unknown;
    GetGameID(): unknown;
    GetLastPlayedSectionName(): unknown;
    GetLastTimePlayed(): unknown;
    GetPerClientData(e: unknown): unknown;
    GetPrimaryAppID(): unknown;
    GetStoreTags(): unknown;
    InitFromProto(e: unknown): void;
    LOG_CHANGE(): unknown /* native code */;
    SetGameID(e: unknown): void;
    SetLastTimePlayed(e: unknown): void;
    SetPerClientData(e: unknown): void;
    SetSortAs(e: unknown): void;
    SetStoreCategories(e: unknown): void;
    SetStoreTags(e: unknown): void;
  
    __cachedLastPlayedSection: undefined;
    __cachedLastPlayedTime: undefined;
    __cachedReleaseYearString: undefined;
    active_beta: undefined;
    album_cover_hash: undefined;
    app_type: number;
    appid: number;
    canonicalAppType: number;
    display_name: string;
    display_status: number;
    gameid: string;
    gamepad_preferred: boolean;
    header_filename: undefined;
    icon_data: undefined;
    icon_data_format: undefined;
    icon_hash: string;
    installed: undefined;
    is_available_on_current_platform: boolean;
    is_invalid_os_type: undefined;
    library_capsule_filename: string;
    library_id: undefined;
    local_cache_version: number;
    local_per_client_data: Local_per_client_data;
    m_gameid: undefined;
    m_setStoreCategories: Set<number>;
    m_setStoreTags: Set<number>;
    m_ulGameId: undefined;
    mastersub_appid: undefined;
    mastersub_includedwith_logo: undefined;
    metacritic_score: number;
    minutes_playtime_forever: number;
    minutes_playtime_last_two_weeks: number;
    most_available_clientid: string;
    most_available_per_client_data: Local_per_client_data;
    mru_index: undefined;
    number_of_copies: number;
    optional_parent_app_id: undefined;
    owner_account_id: undefined;
    per_client_data: Local_per_client_data[];
    ps4_controller_support: number;
    ps5_controller_support: number;
    review_percentage: number;
    review_percentage_with_bombs: number;
    review_percentage_without_bombs: number;
    review_score: number;
    review_score_with_bombs: number;
    review_score_without_bombs: number;
    rt_custom_image_mtime: undefined;
    rt_last_time_locally_played: undefined;
    rt_last_time_played: number;
    rt_last_time_played_or_installed: number;
    rt_original_release_date: number;
    rt_purchased_time: number;
    rt_recent_activity_time: number;
    rt_steam_release_date: number;
    rt_store_asset_mtime: number;
    selected_clientid: string;
    selected_per_client_data: Local_per_client_data;
    shortcut_override_appid: undefined;
    site_license_site_name: undefined;
    size_on_disk: undefined;
    sort_as: string;
    status_percentage: number;
    steam_deck_compat_category: number;
    steam_hw_compat_category_packed: number;
    store_category: number[];
    store_tag: number[];
    subscribed_to: boolean;
    third_party_mod: undefined;
    visible_in_game_list: boolean;
    vr_only: undefined;
    vr_supported: undefined;
    xbox_controller_support: number;
  }
  
  export interface Collection3 {
    BAreCategoriesEqual(e: unknown): unknown;
    BAreSetsEqual(e: unknown, t: unknown): unknown;
    BAreStoreTagsEqual(e: unknown): unknown;
    BHasCustomImages(): boolean;
    BHasNonObservableChange(e: unknown): boolean;
    BHasObservableChange(e: unknown): boolean;
    BHasObservables(): boolean;
    BHasStoreCategory(e: unknown): unknown;
    BHasStoreTag(): unknown /* native code */;
    BIsAppBlocked(): unknown;
    BIsAppInBlockList(): unknown;
    BIsApplicationOrTool(): boolean;
    BIsBorrowed(): unknown;
    BIsDemo(): boolean;
    BIsGameIDEqual(e: unknown): boolean;
    BIsHardware(): boolean;
    BIsLastTimePlayedEqual(e: unknown): boolean;
    BIsModOrShortcut(): unknown;
    BIsMusicAlbum(): boolean;
    BIsNewToLibrary(): unknown;
    BIsOwned(): unknown;
    BIsOwnedByAnotherUser(): unknown;
    BIsPerClientDataEqual(e: unknown): boolean;
    BIsPerClientDataLocal(e: unknown): unknown;
    BIsSelectedClientLocal(): boolean;
    BIsShortcut(): boolean;
    BIsSortAsEqual(e: unknown): boolean;
    BIsSteamDeckVerified(): boolean;
    BIsSteamVR(): unknown;
    BIsUnreleased(): boolean;
    BIsVisibleInMRUList(): boolean;
    BSupportsVR(): unknown;
    ComputeLastPlayedSectionName(e: unknown): unknown;
    GetCanonicalReleaseDate(): unknown;
    GetCanonicalReleaseYear(): unknown;
    GetGameID(): unknown;
    GetLastPlayedSectionName(): unknown;
    GetLastTimePlayed(): unknown;
    GetPerClientData(e: unknown): unknown;
    GetPrimaryAppID(): unknown;
    GetStoreTags(): unknown;
    InitFromProto(e: unknown): void;
    LOG_CHANGE(): unknown /* native code */;
    SetGameID(e: unknown): void;
    SetLastTimePlayed(e: unknown): void;
    SetPerClientData(e: unknown): void;
    SetSortAs(e: unknown): void;
    SetStoreCategories(e: unknown): void;
    SetStoreTags(e: unknown): void;
  
    __cachedLastPlayedSection: undefined;
    __cachedLastPlayedTime: undefined;
    __cachedReleaseYearString: undefined;
    active_beta: undefined;
    album_cover_hash: undefined;
    app_type: number;
    appid: number;
    canonicalAppType: number;
    display_name: string;
    display_status: number;
    gameid: string;
    gamepad_preferred: boolean;
    header_filename: string;
    icon_data: undefined;
    icon_data_format: undefined;
    icon_hash: string;
    installed: boolean;
    is_available_on_current_platform: boolean;
    is_invalid_os_type: undefined;
    library_capsule_filename: string;
    library_id: string;
    local_cache_version: number;
    local_per_client_data: Local_per_client_data2;
    m_gameid: undefined;
    m_setStoreCategories: Set<number>;
    m_setStoreTags: Set<number>;
    m_ulGameId: undefined;
    mastersub_appid: undefined;
    mastersub_includedwith_logo: undefined;
    metacritic_score: number;
    minutes_playtime_forever: number;
    minutes_playtime_last_two_weeks: number;
    most_available_clientid: string;
    most_available_per_client_data: Local_per_client_data2;
    mru_index: undefined;
    number_of_copies: number;
    optional_parent_app_id: undefined;
    owner_account_id: undefined;
    per_client_data: Local_per_client_data2[];
    ps4_controller_support: number;
    ps5_controller_support: number;
    review_percentage: number;
    review_percentage_with_bombs: number;
    review_percentage_without_bombs: number;
    review_score: number;
    review_score_with_bombs: number;
    review_score_without_bombs: number;
    rt_custom_image_mtime: undefined;
    rt_last_time_locally_played: undefined;
    rt_last_time_played: number;
    rt_last_time_played_or_installed: number;
    rt_original_release_date: number;
    rt_purchased_time: number;
    rt_recent_activity_time: number;
    rt_steam_release_date: number;
    rt_store_asset_mtime: number;
    selected_clientid: string;
    selected_per_client_data: Local_per_client_data2;
    shortcut_override_appid: undefined;
    site_license_site_name: undefined;
    size_on_disk: string;
    sort_as: string;
    status_percentage: number;
    steam_deck_compat_category: number;
    steam_hw_compat_category_packed: number;
    store_category: number[];
    store_tag: number[];
    subscribed_to: boolean;
    third_party_mod: undefined;
    visible_in_game_list: boolean;
    vr_only: undefined;
    vr_supported: undefined;
    xbox_controller_support: number;
  }
  
  export interface Collection4 {
    BAreCategoriesEqual(e: unknown): unknown;
    BAreSetsEqual(e: unknown, t: unknown): unknown;
    BAreStoreTagsEqual(e: unknown): unknown;
    BHasCustomImages(): boolean;
    BHasNonObservableChange(e: unknown): boolean;
    BHasObservableChange(e: unknown): boolean;
    BHasObservables(): boolean;
    BHasStoreCategory(e: unknown): unknown;
    BHasStoreTag(): unknown /* native code */;
    BIsAppBlocked(): unknown;
    BIsAppInBlockList(): unknown;
    BIsApplicationOrTool(): boolean;
    BIsBorrowed(): unknown;
    BIsDemo(): boolean;
    BIsGameIDEqual(e: unknown): boolean;
    BIsHardware(): boolean;
    BIsLastTimePlayedEqual(e: unknown): boolean;
    BIsModOrShortcut(): unknown;
    BIsMusicAlbum(): boolean;
    BIsNewToLibrary(): unknown;
    BIsOwned(): unknown;
    BIsOwnedByAnotherUser(): unknown;
    BIsPerClientDataEqual(e: unknown): boolean;
    BIsPerClientDataLocal(e: unknown): unknown;
    BIsSelectedClientLocal(): boolean;
    BIsShortcut(): boolean;
    BIsSortAsEqual(e: unknown): boolean;
    BIsSteamDeckVerified(): boolean;
    BIsSteamVR(): unknown;
    BIsUnreleased(): boolean;
    BIsVisibleInMRUList(): boolean;
    BSupportsVR(): unknown;
    ComputeLastPlayedSectionName(e: unknown): unknown;
    GetCanonicalReleaseDate(): unknown;
    GetCanonicalReleaseYear(): unknown;
    GetGameID(): unknown;
    GetLastPlayedSectionName(): unknown;
    GetLastTimePlayed(): unknown;
    GetPerClientData(e: unknown): unknown;
    GetPrimaryAppID(): unknown;
    GetStoreTags(): unknown;
    InitFromProto(e: unknown): void;
    LOG_CHANGE(): unknown /* native code */;
    SetGameID(e: unknown): void;
    SetLastTimePlayed(e: unknown): void;
    SetPerClientData(e: unknown): void;
    SetSortAs(e: unknown): void;
    SetStoreCategories(e: unknown): void;
    SetStoreTags(e: unknown): void;
  
    __cachedLastPlayedSection: undefined;
    __cachedLastPlayedTime: undefined;
    __cachedReleaseYearString: undefined;
    active_beta: undefined;
    album_cover_hash: undefined;
    app_type: number;
    appid: number;
    canonicalAppType: number;
    display_name: string;
    display_status: number;
    gameid: string;
    gamepad_preferred: boolean;
    header_filename: undefined;
    icon_data: undefined;
    icon_data_format: undefined;
    icon_hash: string;
    installed: boolean;
    is_available_on_current_platform: boolean;
    is_invalid_os_type: undefined;
    library_capsule_filename: string;
    library_id: string;
    local_cache_version: number;
    local_per_client_data: Local_per_client_data2;
    m_gameid: undefined;
    m_setStoreCategories: Set<number>;
    m_setStoreTags: Set<number>;
    m_ulGameId: undefined;
    mastersub_appid: undefined;
    mastersub_includedwith_logo: undefined;
    metacritic_score: number;
    minutes_playtime_forever: number;
    minutes_playtime_last_two_weeks: number;
    most_available_clientid: string;
    most_available_per_client_data: Local_per_client_data2;
    mru_index: undefined;
    number_of_copies: number;
    optional_parent_app_id: undefined;
    owner_account_id: undefined;
    per_client_data: Local_per_client_data2[];
    ps4_controller_support: number;
    ps5_controller_support: number;
    review_percentage: number;
    review_percentage_with_bombs: number;
    review_percentage_without_bombs: number;
    review_score: number;
    review_score_with_bombs: number;
    review_score_without_bombs: number;
    rt_custom_image_mtime: undefined;
    rt_last_time_locally_played: undefined;
    rt_last_time_played: number;
    rt_last_time_played_or_installed: number;
    rt_original_release_date: number;
    rt_purchased_time: number;
    rt_recent_activity_time: number;
    rt_steam_release_date: number;
    rt_store_asset_mtime: number;
    selected_clientid: string;
    selected_per_client_data: Local_per_client_data2;
    shortcut_override_appid: undefined;
    site_license_site_name: undefined;
    size_on_disk: string;
    sort_as: string;
    status_percentage: number;
    steam_deck_compat_category: number;
    steam_hw_compat_category_packed: number;
    store_category: number[];
    store_tag: number[];
    subscribed_to: boolean;
    third_party_mod: undefined;
    visible_in_game_list: boolean;
    vr_only: undefined;
    vr_supported: undefined;
    xbox_controller_support: number;
  }
  
  export interface Collection5 {
    BAreCategoriesEqual(e: unknown): unknown;
    BAreSetsEqual(e: unknown, t: unknown): unknown;
    BAreStoreTagsEqual(e: unknown): unknown;
    BHasCustomImages(): boolean;
    BHasNonObservableChange(e: unknown): boolean;
    BHasObservableChange(e: unknown): boolean;
    BHasObservables(): boolean;
    BHasStoreCategory(e: unknown): unknown;
    BHasStoreTag(): unknown /* native code */;
    BIsAppBlocked(): unknown;
    BIsAppInBlockList(): unknown;
    BIsApplicationOrTool(): boolean;
    BIsBorrowed(): unknown;
    BIsDemo(): boolean;
    BIsGameIDEqual(e: unknown): boolean;
    BIsHardware(): boolean;
    BIsLastTimePlayedEqual(e: unknown): boolean;
    BIsModOrShortcut(): unknown;
    BIsMusicAlbum(): boolean;
    BIsNewToLibrary(): unknown;
    BIsOwned(): unknown;
    BIsOwnedByAnotherUser(): unknown;
    BIsPerClientDataEqual(e: unknown): boolean;
    BIsPerClientDataLocal(e: unknown): unknown;
    BIsSelectedClientLocal(): boolean;
    BIsShortcut(): boolean;
    BIsSortAsEqual(e: unknown): boolean;
    BIsSteamDeckVerified(): boolean;
    BIsSteamVR(): unknown;
    BIsUnreleased(): boolean;
    BIsVisibleInMRUList(): boolean;
    BSupportsVR(): unknown;
    ComputeLastPlayedSectionName(e: unknown): unknown;
    GetCanonicalReleaseDate(): unknown;
    GetCanonicalReleaseYear(): unknown;
    GetGameID(): unknown;
    GetLastPlayedSectionName(): unknown;
    GetLastTimePlayed(): unknown;
    GetPerClientData(e: unknown): unknown;
    GetPrimaryAppID(): unknown;
    GetStoreTags(): unknown;
    InitFromProto(e: unknown): void;
    LOG_CHANGE(): unknown /* native code */;
    SetGameID(e: unknown): void;
    SetLastTimePlayed(e: unknown): void;
    SetPerClientData(e: unknown): void;
    SetSortAs(e: unknown): void;
    SetStoreCategories(e: unknown): void;
    SetStoreTags(e: unknown): void;
  
    __cachedLastPlayedSection: undefined;
    __cachedLastPlayedTime: undefined;
    __cachedReleaseYearString: undefined;
    active_beta: undefined;
    album_cover_hash: undefined;
    app_type: number;
    appid: number;
    canonicalAppType: number;
    display_name: string;
    display_status: number;
    gameid: string;
    gamepad_preferred: boolean;
    header_filename: undefined;
    icon_data: undefined;
    icon_data_format: undefined;
    icon_hash: string;
    installed: boolean;
    is_available_on_current_platform: boolean;
    is_invalid_os_type: undefined;
    library_capsule_filename: string;
    library_id: string;
    local_cache_version: number;
    local_per_client_data: Local_per_client_data2;
    m_gameid: undefined;
    m_setStoreCategories: Set<number>;
    m_setStoreTags: Set<number>;
    m_ulGameId: undefined;
    mastersub_appid: undefined;
    mastersub_includedwith_logo: undefined;
    metacritic_score: number;
    minutes_playtime_forever: number;
    minutes_playtime_last_two_weeks: number;
    most_available_clientid: string;
    most_available_per_client_data: Local_per_client_data2;
    mru_index: undefined;
    number_of_copies: number;
    optional_parent_app_id: undefined;
    owner_account_id: undefined;
    per_client_data: Local_per_client_data2[];
    ps4_controller_support: number;
    ps5_controller_support: number;
    review_percentage: number;
    review_percentage_with_bombs: number;
    review_percentage_without_bombs: number;
    review_score: number;
    review_score_with_bombs: number;
    review_score_without_bombs: number;
    rt_custom_image_mtime: number;
    rt_last_time_locally_played: undefined;
    rt_last_time_played: number;
    rt_last_time_played_or_installed: number;
    rt_original_release_date: number;
    rt_purchased_time: number;
    rt_recent_activity_time: number;
    rt_steam_release_date: number;
    rt_store_asset_mtime: number;
    selected_clientid: string;
    selected_per_client_data: Local_per_client_data2;
    shortcut_override_appid: undefined;
    site_license_site_name: undefined;
    size_on_disk: string;
    sort_as: string;
    status_percentage: number;
    steam_deck_compat_category: number;
    steam_hw_compat_category_packed: number;
    store_category: number[];
    store_tag: number[];
    subscribed_to: boolean;
    third_party_mod: undefined;
    visible_in_game_list: boolean;
    vr_only: undefined;
    vr_supported: undefined;
    xbox_controller_support: number;
  }
  
  export interface Collection6 {
    BAreCategoriesEqual(e: unknown): unknown;
    BAreSetsEqual(e: unknown, t: unknown): unknown;
    BAreStoreTagsEqual(e: unknown): unknown;
    BHasCustomImages(): boolean;
    BHasNonObservableChange(e: unknown): boolean;
    BHasObservableChange(e: unknown): boolean;
    BHasObservables(): boolean;
    BHasStoreCategory(e: unknown): unknown;
    BHasStoreTag(): unknown /* native code */;
    BIsAppBlocked(): unknown;
    BIsAppInBlockList(): unknown;
    BIsApplicationOrTool(): boolean;
    BIsBorrowed(): unknown;
    BIsDemo(): boolean;
    BIsGameIDEqual(e: unknown): boolean;
    BIsHardware(): boolean;
    BIsLastTimePlayedEqual(e: unknown): boolean;
    BIsModOrShortcut(): unknown;
    BIsMusicAlbum(): boolean;
    BIsNewToLibrary(): unknown;
    BIsOwned(): unknown;
    BIsOwnedByAnotherUser(): unknown;
    BIsPerClientDataEqual(e: unknown): boolean;
    BIsPerClientDataLocal(e: unknown): unknown;
    BIsSelectedClientLocal(): boolean;
    BIsShortcut(): boolean;
    BIsSortAsEqual(e: unknown): boolean;
    BIsSteamDeckVerified(): boolean;
    BIsSteamVR(): unknown;
    BIsUnreleased(): boolean;
    BIsVisibleInMRUList(): boolean;
    BSupportsVR(): unknown;
    ComputeLastPlayedSectionName(e: unknown): unknown;
    GetCanonicalReleaseDate(): unknown;
    GetCanonicalReleaseYear(): unknown;
    GetGameID(): unknown;
    GetLastPlayedSectionName(): unknown;
    GetLastTimePlayed(): unknown;
    GetPerClientData(e: unknown): unknown;
    GetPrimaryAppID(): unknown;
    GetStoreTags(): unknown;
    InitFromProto(e: unknown): void;
    LOG_CHANGE(): unknown /* native code */;
    SetGameID(e: unknown): void;
    SetLastTimePlayed(e: unknown): void;
    SetPerClientData(e: unknown): void;
    SetSortAs(e: unknown): void;
    SetStoreCategories(e: unknown): void;
    SetStoreTags(e: unknown): void;
  
    __cachedLastPlayedSection: undefined;
    __cachedLastPlayedTime: undefined;
    __cachedReleaseYearString: undefined;
    active_beta: undefined;
    album_cover_hash: undefined;
    app_type: number;
    appid: number;
    canonicalAppType: number;
    display_name: string;
    display_status: number;
    gameid: string;
    gamepad_preferred: boolean;
    header_filename: undefined;
    icon_data: undefined;
    icon_data_format: undefined;
    icon_hash: string;
    installed: boolean;
    is_available_on_current_platform: boolean;
    is_invalid_os_type: undefined;
    library_capsule_filename: string;
    library_id: string;
    local_cache_version: number;
    local_per_client_data: Local_per_client_data2;
    m_gameid: undefined;
    m_setStoreCategories: Set<number>;
    m_setStoreTags: Set<number>;
    m_ulGameId: undefined;
    mastersub_appid: undefined;
    mastersub_includedwith_logo: undefined;
    metacritic_score: undefined;
    minutes_playtime_forever: number;
    minutes_playtime_last_two_weeks: number;
    most_available_clientid: string;
    most_available_per_client_data: Local_per_client_data2;
    mru_index: undefined;
    number_of_copies: number;
    optional_parent_app_id: undefined;
    owner_account_id: undefined;
    per_client_data: Local_per_client_data2[];
    ps4_controller_support: number;
    ps5_controller_support: number;
    review_percentage: number;
    review_percentage_with_bombs: number;
    review_percentage_without_bombs: number;
    review_score: number;
    review_score_with_bombs: number;
    review_score_without_bombs: number;
    rt_custom_image_mtime: undefined;
    rt_last_time_locally_played: undefined;
    rt_last_time_played: number;
    rt_last_time_played_or_installed: number;
    rt_original_release_date: number;
    rt_purchased_time: number;
    rt_recent_activity_time: number;
    rt_steam_release_date: number;
    rt_store_asset_mtime: number;
    selected_clientid: string;
    selected_per_client_data: Local_per_client_data2;
    shortcut_override_appid: undefined;
    site_license_site_name: undefined;
    size_on_disk: string;
    sort_as: string;
    status_percentage: number;
    steam_deck_compat_category: number;
    steam_hw_compat_category_packed: number;
    store_category: number[];
    store_tag: number[];
    subscribed_to: boolean;
    third_party_mod: undefined;
    visible_in_game_list: boolean;
    vr_only: undefined;
    vr_supported: undefined;
    xbox_controller_support: number;
  }
  
  export interface Collection7 {
    BAreCategoriesEqual(e: unknown): unknown;
    BAreSetsEqual(e: unknown, t: unknown): unknown;
    BAreStoreTagsEqual(e: unknown): unknown;
    BHasCustomImages(): boolean;
    BHasNonObservableChange(e: unknown): boolean;
    BHasObservableChange(e: unknown): boolean;
    BHasObservables(): boolean;
    BHasStoreCategory(e: unknown): unknown;
    BHasStoreTag(): unknown /* native code */;
    BIsAppBlocked(): unknown;
    BIsAppInBlockList(): unknown;
    BIsApplicationOrTool(): boolean;
    BIsBorrowed(): unknown;
    BIsDemo(): boolean;
    BIsGameIDEqual(e: unknown): boolean;
    BIsHardware(): boolean;
    BIsLastTimePlayedEqual(e: unknown): boolean;
    BIsModOrShortcut(): unknown;
    BIsMusicAlbum(): boolean;
    BIsNewToLibrary(): unknown;
    BIsOwned(): unknown;
    BIsOwnedByAnotherUser(): unknown;
    BIsPerClientDataEqual(e: unknown): boolean;
    BIsPerClientDataLocal(e: unknown): unknown;
    BIsSelectedClientLocal(): boolean;
    BIsShortcut(): boolean;
    BIsSortAsEqual(e: unknown): boolean;
    BIsSteamDeckVerified(): boolean;
    BIsSteamVR(): unknown;
    BIsUnreleased(): boolean;
    BIsVisibleInMRUList(): boolean;
    BSupportsVR(): unknown;
    ComputeLastPlayedSectionName(e: unknown): unknown;
    GetCanonicalReleaseDate(): unknown;
    GetCanonicalReleaseYear(): unknown;
    GetGameID(): unknown;
    GetLastPlayedSectionName(): unknown;
    GetLastTimePlayed(): unknown;
    GetPerClientData(e: unknown): unknown;
    GetPrimaryAppID(): unknown;
    GetStoreTags(): unknown;
    InitFromProto(e: unknown): void;
    LOG_CHANGE(): unknown /* native code */;
    SetGameID(e: unknown): void;
    SetLastTimePlayed(e: unknown): void;
    SetPerClientData(e: unknown): void;
    SetSortAs(e: unknown): void;
    SetStoreCategories(e: unknown): void;
    SetStoreTags(e: unknown): void;
  
    __cachedLastPlayedSection: undefined;
    __cachedLastPlayedTime: undefined;
    __cachedReleaseYearString: undefined;
    active_beta: undefined;
    album_cover_hash: undefined;
    app_type: number;
    appid: number;
    canonicalAppType: number;
    display_name: string;
    display_status: number;
    gameid: string;
    gamepad_preferred: boolean;
    header_filename: string;
    icon_data: undefined;
    icon_data_format: undefined;
    icon_hash: string;
    installed: boolean;
    is_available_on_current_platform: boolean;
    is_invalid_os_type: undefined;
    library_capsule_filename: string;
    library_id: string;
    local_cache_version: number;
    local_per_client_data: Local_per_client_data2;
    m_gameid: undefined;
    m_setStoreCategories: Set<number>;
    m_setStoreTags: Set<number>;
    m_ulGameId: undefined;
    mastersub_appid: undefined;
    mastersub_includedwith_logo: undefined;
    metacritic_score: undefined;
    minutes_playtime_forever: number;
    minutes_playtime_last_two_weeks: number;
    most_available_clientid: string;
    most_available_per_client_data: Local_per_client_data2;
    mru_index: undefined;
    number_of_copies: number;
    optional_parent_app_id: undefined;
    owner_account_id: undefined;
    per_client_data: Local_per_client_data2[];
    ps4_controller_support: number;
    ps5_controller_support: number;
    review_percentage: number;
    review_percentage_with_bombs: number;
    review_percentage_without_bombs: number;
    review_score: number;
    review_score_with_bombs: number;
    review_score_without_bombs: number;
    rt_custom_image_mtime: undefined;
    rt_last_time_locally_played: undefined;
    rt_last_time_played: number;
    rt_last_time_played_or_installed: number;
    rt_original_release_date: number;
    rt_purchased_time: number;
    rt_recent_activity_time: number;
    rt_steam_release_date: number;
    rt_store_asset_mtime: number;
    selected_clientid: string;
    selected_per_client_data: Local_per_client_data2;
    shortcut_override_appid: undefined;
    site_license_site_name: undefined;
    size_on_disk: string;
    sort_as: string;
    status_percentage: number;
    steam_deck_compat_category: number;
    steam_hw_compat_category_packed: number;
    store_category: number[];
    store_tag: number[];
    subscribed_to: boolean;
    third_party_mod: undefined;
    visible_in_game_list: boolean;
    vr_only: undefined;
    vr_supported: undefined;
    xbox_controller_support: undefined;
  }
  
  export interface Collection8 {
    BAreCategoriesEqual(e: unknown): unknown;
    BAreSetsEqual(e: unknown, t: unknown): unknown;
    BAreStoreTagsEqual(e: unknown): unknown;
    BHasCustomImages(): boolean;
    BHasNonObservableChange(e: unknown): boolean;
    BHasObservableChange(e: unknown): boolean;
    BHasObservables(): boolean;
    BHasStoreCategory(e: unknown): unknown;
    BHasStoreTag(): unknown /* native code */;
    BIsAppBlocked(): unknown;
    BIsAppInBlockList(): unknown;
    BIsApplicationOrTool(): boolean;
    BIsBorrowed(): unknown;
    BIsDemo(): boolean;
    BIsGameIDEqual(e: unknown): boolean;
    BIsHardware(): boolean;
    BIsLastTimePlayedEqual(e: unknown): boolean;
    BIsModOrShortcut(): unknown;
    BIsMusicAlbum(): boolean;
    BIsNewToLibrary(): unknown;
    BIsOwned(): unknown;
    BIsOwnedByAnotherUser(): unknown;
    BIsPerClientDataEqual(e: unknown): boolean;
    BIsPerClientDataLocal(e: unknown): unknown;
    BIsSelectedClientLocal(): boolean;
    BIsShortcut(): boolean;
    BIsSortAsEqual(e: unknown): boolean;
    BIsSteamDeckVerified(): boolean;
    BIsSteamVR(): unknown;
    BIsUnreleased(): boolean;
    BIsVisibleInMRUList(): boolean;
    BSupportsVR(): unknown;
    ComputeLastPlayedSectionName(e: unknown): unknown;
    GetCanonicalReleaseDate(): unknown;
    GetCanonicalReleaseYear(): unknown;
    GetGameID(): unknown;
    GetLastPlayedSectionName(): unknown;
    GetLastTimePlayed(): unknown;
    GetPerClientData(e: unknown): unknown;
    GetPrimaryAppID(): unknown;
    GetStoreTags(): unknown;
    InitFromProto(e: unknown): void;
    LOG_CHANGE(): unknown /* native code */;
    SetGameID(e: unknown): void;
    SetLastTimePlayed(e: unknown): void;
    SetPerClientData(e: unknown): void;
    SetSortAs(e: unknown): void;
    SetStoreCategories(e: unknown): void;
    SetStoreTags(e: unknown): void;
  
    __cachedLastPlayedSection: undefined;
    __cachedLastPlayedTime: undefined;
    __cachedReleaseYearString: undefined;
    active_beta: undefined;
    album_cover_hash: undefined;
    app_type: number;
    appid: number;
    canonicalAppType: number;
    display_name: string;
    display_status: number;
    gameid: string;
    gamepad_preferred: boolean;
    header_filename: undefined;
    icon_data: undefined;
    icon_data_format: undefined;
    icon_hash: string;
    installed: boolean;
    is_available_on_current_platform: boolean;
    is_invalid_os_type: undefined;
    library_capsule_filename: string;
    library_id: string;
    local_cache_version: number;
    local_per_client_data: Local_per_client_data2;
    m_gameid: undefined;
    m_setStoreCategories: Set<number>;
    m_setStoreTags: Set<number>;
    m_ulGameId: undefined;
    mastersub_appid: undefined;
    mastersub_includedwith_logo: undefined;
    metacritic_score: undefined;
    minutes_playtime_forever: number;
    minutes_playtime_last_two_weeks: number;
    most_available_clientid: string;
    most_available_per_client_data: Local_per_client_data2;
    mru_index: number;
    number_of_copies: number;
    optional_parent_app_id: undefined;
    owner_account_id: undefined;
    per_client_data: Local_per_client_data2[];
    ps4_controller_support: number;
    ps5_controller_support: number;
    review_percentage: number;
    review_percentage_with_bombs: number;
    review_percentage_without_bombs: number;
    review_score: number;
    review_score_with_bombs: number;
    review_score_without_bombs: number;
    rt_custom_image_mtime: undefined;
    rt_last_time_locally_played: number;
    rt_last_time_played: number;
    rt_last_time_played_or_installed: number;
    rt_original_release_date: number;
    rt_purchased_time: number;
    rt_recent_activity_time: number;
    rt_steam_release_date: number;
    rt_store_asset_mtime: number;
    selected_clientid: string;
    selected_per_client_data: Local_per_client_data2;
    shortcut_override_appid: undefined;
    site_license_site_name: undefined;
    size_on_disk: string;
    sort_as: string;
    status_percentage: number;
    steam_deck_compat_category: number;
    steam_hw_compat_category_packed: number;
    store_category: number[];
    store_tag: number[];
    subscribed_to: boolean;
    third_party_mod: undefined;
    visible_in_game_list: boolean;
    vr_only: undefined;
    vr_supported: undefined;
    xbox_controller_support: undefined;
  }
  
  export interface Collection9 {
    BAreCategoriesEqual(e: unknown): unknown;
    BAreSetsEqual(e: unknown, t: unknown): unknown;
    BAreStoreTagsEqual(e: unknown): unknown;
    BHasCustomImages(): boolean;
    BHasNonObservableChange(e: unknown): boolean;
    BHasObservableChange(e: unknown): boolean;
    BHasObservables(): boolean;
    BHasStoreCategory(e: unknown): unknown;
    BHasStoreTag(): unknown /* native code */;
    BIsAppBlocked(): unknown;
    BIsAppInBlockList(): unknown;
    BIsApplicationOrTool(): boolean;
    BIsBorrowed(): unknown;
    BIsDemo(): boolean;
    BIsGameIDEqual(e: unknown): boolean;
    BIsHardware(): boolean;
    BIsLastTimePlayedEqual(e: unknown): boolean;
    BIsModOrShortcut(): unknown;
    BIsMusicAlbum(): boolean;
    BIsNewToLibrary(): unknown;
    BIsOwned(): unknown;
    BIsOwnedByAnotherUser(): unknown;
    BIsPerClientDataEqual(e: unknown): boolean;
    BIsPerClientDataLocal(e: unknown): unknown;
    BIsSelectedClientLocal(): boolean;
    BIsShortcut(): boolean;
    BIsSortAsEqual(e: unknown): boolean;
    BIsSteamDeckVerified(): boolean;
    BIsSteamVR(): unknown;
    BIsUnreleased(): boolean;
    BIsVisibleInMRUList(): boolean;
    BSupportsVR(): unknown;
    ComputeLastPlayedSectionName(e: unknown): unknown;
    GetCanonicalReleaseDate(): unknown;
    GetCanonicalReleaseYear(): unknown;
    GetGameID(): unknown;
    GetLastPlayedSectionName(): unknown;
    GetLastTimePlayed(): unknown;
    GetPerClientData(e: unknown): unknown;
    GetPrimaryAppID(): unknown;
    GetStoreTags(): unknown;
    InitFromProto(e: unknown): void;
    LOG_CHANGE(): unknown /* native code */;
    SetGameID(e: unknown): void;
    SetLastTimePlayed(e: unknown): void;
    SetPerClientData(e: unknown): void;
    SetSortAs(e: unknown): void;
    SetStoreCategories(e: unknown): void;
    SetStoreTags(e: unknown): void;
  
    __cachedLastPlayedSection: undefined;
    __cachedLastPlayedTime: undefined;
    __cachedReleaseYearString: undefined;
    active_beta: undefined;
    album_cover_hash: undefined;
    app_type: number;
    appid: number;
    canonicalAppType: number;
    display_name: string;
    display_status: number;
    gameid: string;
    gamepad_preferred: boolean;
    header_filename: string;
    icon_data: undefined;
    icon_data_format: undefined;
    icon_hash: string;
    installed: boolean;
    is_available_on_current_platform: boolean;
    is_invalid_os_type: undefined;
    library_capsule_filename: string;
    library_id: string;
    local_cache_version: number;
    local_per_client_data: Local_per_client_data2;
    m_gameid: undefined;
    m_setStoreCategories: Set<number>;
    m_setStoreTags: Set<number>;
    m_ulGameId: undefined;
    mastersub_appid: undefined;
    mastersub_includedwith_logo: undefined;
    metacritic_score: undefined;
    minutes_playtime_forever: number;
    minutes_playtime_last_two_weeks: number;
    most_available_clientid: string;
    most_available_per_client_data: Local_per_client_data2;
    mru_index: number;
    number_of_copies: number;
    optional_parent_app_id: undefined;
    owner_account_id: undefined;
    per_client_data: Local_per_client_data2[];
    ps4_controller_support: number;
    ps5_controller_support: number;
    review_percentage: number;
    review_percentage_with_bombs: number;
    review_percentage_without_bombs: number;
    review_score: number;
    review_score_with_bombs: number;
    review_score_without_bombs: number;
    rt_custom_image_mtime: undefined;
    rt_last_time_locally_played: number;
    rt_last_time_played: number;
    rt_last_time_played_or_installed: number;
    rt_original_release_date: number;
    rt_purchased_time: number;
    rt_recent_activity_time: number;
    rt_steam_release_date: number;
    rt_store_asset_mtime: number;
    selected_clientid: string;
    selected_per_client_data: Local_per_client_data2;
    shortcut_override_appid: undefined;
    site_license_site_name: undefined;
    size_on_disk: string;
    sort_as: string;
    status_percentage: number;
    steam_deck_compat_category: number;
    steam_hw_compat_category_packed: number;
    store_category: number[];
    store_tag: number[];
    subscribed_to: boolean;
    third_party_mod: undefined;
    visible_in_game_list: boolean;
    vr_only: undefined;
    vr_supported: undefined;
    xbox_controller_support: undefined;
  }
  
  export interface Collection10 {
    BAreCategoriesEqual(e: unknown): unknown;
    BAreSetsEqual(e: unknown, t: unknown): unknown;
    BAreStoreTagsEqual(e: unknown): unknown;
    BHasCustomImages(): boolean;
    BHasNonObservableChange(e: unknown): boolean;
    BHasObservableChange(e: unknown): boolean;
    BHasObservables(): boolean;
    BHasStoreCategory(e: unknown): unknown;
    BHasStoreTag(): unknown /* native code */;
    BIsAppBlocked(): unknown;
    BIsAppInBlockList(): unknown;
    BIsApplicationOrTool(): boolean;
    BIsBorrowed(): unknown;
    BIsDemo(): boolean;
    BIsGameIDEqual(e: unknown): boolean;
    BIsHardware(): boolean;
    BIsLastTimePlayedEqual(e: unknown): boolean;
    BIsModOrShortcut(): unknown;
    BIsMusicAlbum(): boolean;
    BIsNewToLibrary(): unknown;
    BIsOwned(): unknown;
    BIsOwnedByAnotherUser(): unknown;
    BIsPerClientDataEqual(e: unknown): boolean;
    BIsPerClientDataLocal(e: unknown): unknown;
    BIsSelectedClientLocal(): boolean;
    BIsShortcut(): boolean;
    BIsSortAsEqual(e: unknown): boolean;
    BIsSteamDeckVerified(): boolean;
    BIsSteamVR(): unknown;
    BIsUnreleased(): boolean;
    BIsVisibleInMRUList(): boolean;
    BSupportsVR(): unknown;
    ComputeLastPlayedSectionName(e: unknown): unknown;
    GetCanonicalReleaseDate(): unknown;
    GetCanonicalReleaseYear(): unknown;
    GetGameID(): unknown;
    GetLastPlayedSectionName(): unknown;
    GetLastTimePlayed(): unknown;
    GetPerClientData(e: unknown): unknown;
    GetPrimaryAppID(): unknown;
    GetStoreTags(): unknown;
    InitFromProto(e: unknown): void;
    LOG_CHANGE(): unknown /* native code */;
    SetGameID(e: unknown): void;
    SetLastTimePlayed(e: unknown): void;
    SetPerClientData(e: unknown): void;
    SetSortAs(e: unknown): void;
    SetStoreCategories(e: unknown): void;
    SetStoreTags(e: unknown): void;
  
    __cachedLastPlayedSection: undefined;
    __cachedLastPlayedTime: undefined;
    __cachedReleaseYearString: undefined;
    active_beta: string;
    album_cover_hash: undefined;
    app_type: number;
    appid: number;
    canonicalAppType: number;
    display_name: string;
    display_status: number;
    gameid: string;
    gamepad_preferred: boolean;
    header_filename: string;
    icon_data: undefined;
    icon_data_format: undefined;
    icon_hash: string;
    installed: boolean;
    is_available_on_current_platform: boolean;
    is_invalid_os_type: undefined;
    library_capsule_filename: string;
    library_id: string;
    local_cache_version: number;
    local_per_client_data: Local_per_client_data3;
    m_gameid: undefined;
    m_setStoreCategories: Set<number>;
    m_setStoreTags: Set<number>;
    m_ulGameId: undefined;
    mastersub_appid: undefined;
    mastersub_includedwith_logo: undefined;
    metacritic_score: number;
    minutes_playtime_forever: number;
    minutes_playtime_last_two_weeks: number;
    most_available_clientid: string;
    most_available_per_client_data: Local_per_client_data3;
    mru_index: number;
    number_of_copies: number;
    optional_parent_app_id: undefined;
    owner_account_id: undefined;
    per_client_data: Local_per_client_data3[];
    ps4_controller_support: number;
    ps5_controller_support: number;
    review_percentage: number;
    review_percentage_with_bombs: number;
    review_percentage_without_bombs: number;
    review_score: number;
    review_score_with_bombs: number;
    review_score_without_bombs: number;
    rt_custom_image_mtime: undefined;
    rt_last_time_locally_played: number;
    rt_last_time_played: number;
    rt_last_time_played_or_installed: number;
    rt_original_release_date: number;
    rt_purchased_time: number;
    rt_recent_activity_time: number;
    rt_steam_release_date: number;
    rt_store_asset_mtime: number;
    selected_clientid: string;
    selected_per_client_data: Local_per_client_data3;
    shortcut_override_appid: undefined;
    site_license_site_name: undefined;
    size_on_disk: string;
    sort_as: string;
    status_percentage: number;
    steam_deck_compat_category: number;
    steam_hw_compat_category_packed: number;
    store_category: number[];
    store_tag: number[];
    subscribed_to: boolean;
    third_party_mod: undefined;
    visible_in_game_list: boolean;
    vr_only: undefined;
    vr_supported: boolean;
    xbox_controller_support: number;
  }
  
  export interface Collection11 {
    BAreCategoriesEqual(e: unknown): unknown;
    BAreSetsEqual(e: unknown, t: unknown): unknown;
    BAreStoreTagsEqual(e: unknown): unknown;
    BHasCustomImages(): boolean;
    BHasNonObservableChange(e: unknown): boolean;
    BHasObservableChange(e: unknown): boolean;
    BHasObservables(): boolean;
    BHasStoreCategory(e: unknown): unknown;
    BHasStoreTag(): unknown /* native code */;
    BIsAppBlocked(): unknown;
    BIsAppInBlockList(): unknown;
    BIsApplicationOrTool(): boolean;
    BIsBorrowed(): unknown;
    BIsDemo(): boolean;
    BIsGameIDEqual(e: unknown): boolean;
    BIsHardware(): boolean;
    BIsLastTimePlayedEqual(e: unknown): boolean;
    BIsModOrShortcut(): unknown;
    BIsMusicAlbum(): boolean;
    BIsNewToLibrary(): unknown;
    BIsOwned(): unknown;
    BIsOwnedByAnotherUser(): unknown;
    BIsPerClientDataEqual(e: unknown): boolean;
    BIsPerClientDataLocal(e: unknown): unknown;
    BIsSelectedClientLocal(): boolean;
    BIsShortcut(): boolean;
    BIsSortAsEqual(e: unknown): boolean;
    BIsSteamDeckVerified(): boolean;
    BIsSteamVR(): unknown;
    BIsUnreleased(): boolean;
    BIsVisibleInMRUList(): boolean;
    BSupportsVR(): unknown;
    ComputeLastPlayedSectionName(e: unknown): unknown;
    GetCanonicalReleaseDate(): unknown;
    GetCanonicalReleaseYear(): unknown;
    GetGameID(): unknown;
    GetLastPlayedSectionName(): unknown;
    GetLastTimePlayed(): unknown;
    GetPerClientData(e: unknown): unknown;
    GetPrimaryAppID(): unknown;
    GetStoreTags(): unknown;
    InitFromProto(e: unknown): void;
    LOG_CHANGE(): unknown /* native code */;
    SetGameID(e: unknown): void;
    SetLastTimePlayed(e: unknown): void;
    SetPerClientData(e: unknown): void;
    SetSortAs(e: unknown): void;
    SetStoreCategories(e: unknown): void;
    SetStoreTags(e: unknown): void;
  
    __cachedLastPlayedSection: undefined;
    __cachedLastPlayedTime: undefined;
    __cachedReleaseYearString: undefined;
    active_beta: undefined;
    album_cover_hash: undefined;
    app_type: number;
    appid: number;
    canonicalAppType: number;
    display_name: string;
    display_status: number;
    gameid: string;
    gamepad_preferred: boolean;
    header_filename: string;
    icon_data: undefined;
    icon_data_format: undefined;
    icon_hash: string;
    installed: undefined;
    is_available_on_current_platform: boolean;
    is_invalid_os_type: undefined;
    library_capsule_filename: string;
    library_id: undefined;
    local_cache_version: number;
    local_per_client_data: Local_per_client_data;
    m_gameid: undefined;
    m_setStoreCategories: Set<number>;
    m_setStoreTags: Set<number>;
    m_ulGameId: undefined;
    mastersub_appid: undefined;
    mastersub_includedwith_logo: undefined;
    metacritic_score: number;
    minutes_playtime_forever: number;
    minutes_playtime_last_two_weeks: number;
    most_available_clientid: string;
    most_available_per_client_data: Local_per_client_data;
    mru_index: undefined;
    number_of_copies: number;
    optional_parent_app_id: undefined;
    owner_account_id: undefined;
    per_client_data: Local_per_client_data[];
    ps4_controller_support: number;
    ps5_controller_support: number;
    review_percentage: number;
    review_percentage_with_bombs: number;
    review_percentage_without_bombs: number;
    review_score: number;
    review_score_with_bombs: number;
    review_score_without_bombs: number;
    rt_custom_image_mtime: undefined;
    rt_last_time_locally_played: undefined;
    rt_last_time_played: number;
    rt_last_time_played_or_installed: number;
    rt_original_release_date: number;
    rt_purchased_time: number;
    rt_recent_activity_time: number;
    rt_steam_release_date: number;
    rt_store_asset_mtime: number;
    selected_clientid: string;
    selected_per_client_data: Local_per_client_data;
    shortcut_override_appid: undefined;
    site_license_site_name: undefined;
    size_on_disk: undefined;
    sort_as: string;
    status_percentage: number;
    steam_deck_compat_category: number;
    steam_hw_compat_category_packed: number;
    store_category: number[];
    store_tag: number[];
    subscribed_to: boolean;
    third_party_mod: undefined;
    visible_in_game_list: boolean;
    vr_only: undefined;
    vr_supported: undefined;
    xbox_controller_support: undefined;
  }
  
  export interface Collection12 {
    BAreCategoriesEqual(e: unknown): unknown;
    BAreSetsEqual(e: unknown, t: unknown): unknown;
    BAreStoreTagsEqual(e: unknown): unknown;
    BHasCustomImages(): boolean;
    BHasNonObservableChange(e: unknown): boolean;
    BHasObservableChange(e: unknown): boolean;
    BHasObservables(): boolean;
    BHasStoreCategory(e: unknown): unknown;
    BHasStoreTag(): unknown /* native code */;
    BIsAppBlocked(): unknown;
    BIsAppInBlockList(): unknown;
    BIsApplicationOrTool(): boolean;
    BIsBorrowed(): unknown;
    BIsDemo(): boolean;
    BIsGameIDEqual(e: unknown): boolean;
    BIsHardware(): boolean;
    BIsLastTimePlayedEqual(e: unknown): boolean;
    BIsModOrShortcut(): unknown;
    BIsMusicAlbum(): boolean;
    BIsNewToLibrary(): unknown;
    BIsOwned(): unknown;
    BIsOwnedByAnotherUser(): unknown;
    BIsPerClientDataEqual(e: unknown): boolean;
    BIsPerClientDataLocal(e: unknown): unknown;
    BIsSelectedClientLocal(): boolean;
    BIsShortcut(): boolean;
    BIsSortAsEqual(e: unknown): boolean;
    BIsSteamDeckVerified(): boolean;
    BIsSteamVR(): unknown;
    BIsUnreleased(): boolean;
    BIsVisibleInMRUList(): boolean;
    BSupportsVR(): unknown;
    ComputeLastPlayedSectionName(e: unknown): unknown;
    GetCanonicalReleaseDate(): unknown;
    GetCanonicalReleaseYear(): unknown;
    GetGameID(): unknown;
    GetLastPlayedSectionName(): unknown;
    GetLastTimePlayed(): unknown;
    GetPerClientData(e: unknown): unknown;
    GetPrimaryAppID(): unknown;
    GetStoreTags(): unknown;
    InitFromProto(e: unknown): void;
    LOG_CHANGE(): unknown /* native code */;
    SetGameID(e: unknown): void;
    SetLastTimePlayed(e: unknown): void;
    SetPerClientData(e: unknown): void;
    SetSortAs(e: unknown): void;
    SetStoreCategories(e: unknown): void;
    SetStoreTags(e: unknown): void;
  
    __cachedLastPlayedSection: undefined;
    __cachedLastPlayedTime: undefined;
    __cachedReleaseYearString: undefined;
    active_beta: undefined;
    album_cover_hash: undefined;
    app_type: number;
    appid: number;
    canonicalAppType: number;
    display_name: string;
    display_status: number;
    gameid: string;
    gamepad_preferred: boolean;
    header_filename: string;
    icon_data: undefined;
    icon_data_format: undefined;
    icon_hash: string;
    installed: boolean;
    is_available_on_current_platform: boolean;
    is_invalid_os_type: undefined;
    library_capsule_filename: string;
    library_id: string;
    local_cache_version: number;
    local_per_client_data: Local_per_client_data2;
    m_gameid: undefined;
    m_setStoreCategories: Set<number>;
    m_setStoreTags: Set<number>;
    m_ulGameId: undefined;
    mastersub_appid: undefined;
    mastersub_includedwith_logo: undefined;
    metacritic_score: undefined;
    minutes_playtime_forever: number;
    minutes_playtime_last_two_weeks: number;
    most_available_clientid: string;
    most_available_per_client_data: Local_per_client_data2;
    mru_index: undefined;
    number_of_copies: number;
    optional_parent_app_id: undefined;
    owner_account_id: undefined;
    per_client_data: Local_per_client_data2[];
    ps4_controller_support: number;
    ps5_controller_support: number;
    review_percentage: number;
    review_percentage_with_bombs: number;
    review_percentage_without_bombs: number;
    review_score: number;
    review_score_with_bombs: number;
    review_score_without_bombs: number;
    rt_custom_image_mtime: undefined;
    rt_last_time_locally_played: undefined;
    rt_last_time_played: number;
    rt_last_time_played_or_installed: number;
    rt_original_release_date: number;
    rt_purchased_time: undefined;
    rt_recent_activity_time: number;
    rt_steam_release_date: number;
    rt_store_asset_mtime: number;
    selected_clientid: string;
    selected_per_client_data: Local_per_client_data2;
    shortcut_override_appid: undefined;
    site_license_site_name: undefined;
    size_on_disk: string;
    sort_as: string;
    status_percentage: number;
    steam_deck_compat_category: number;
    steam_hw_compat_category_packed: number;
    store_category: number[];
    store_tag: number[];
    subscribed_to: boolean;
    third_party_mod: undefined;
    visible_in_game_list: boolean;
    vr_only: undefined;
    vr_supported: undefined;
    xbox_controller_support: undefined;
  }
  
  export interface Collection13 {
    BAreCategoriesEqual(e: unknown): unknown;
    BAreSetsEqual(e: unknown, t: unknown): unknown;
    BAreStoreTagsEqual(e: unknown): unknown;
    BHasCustomImages(): boolean;
    BHasNonObservableChange(e: unknown): boolean;
    BHasObservableChange(e: unknown): boolean;
    BHasObservables(): boolean;
    BHasStoreCategory(e: unknown): unknown;
    BHasStoreTag(): unknown /* native code */;
    BIsAppBlocked(): unknown;
    BIsAppInBlockList(): unknown;
    BIsApplicationOrTool(): boolean;
    BIsBorrowed(): unknown;
    BIsDemo(): boolean;
    BIsGameIDEqual(e: unknown): boolean;
    BIsHardware(): boolean;
    BIsLastTimePlayedEqual(e: unknown): boolean;
    BIsModOrShortcut(): unknown;
    BIsMusicAlbum(): boolean;
    BIsNewToLibrary(): unknown;
    BIsOwned(): unknown;
    BIsOwnedByAnotherUser(): unknown;
    BIsPerClientDataEqual(e: unknown): boolean;
    BIsPerClientDataLocal(e: unknown): unknown;
    BIsSelectedClientLocal(): boolean;
    BIsShortcut(): boolean;
    BIsSortAsEqual(e: unknown): boolean;
    BIsSteamDeckVerified(): boolean;
    BIsSteamVR(): unknown;
    BIsUnreleased(): boolean;
    BIsVisibleInMRUList(): boolean;
    BSupportsVR(): unknown;
    ComputeLastPlayedSectionName(e: unknown): unknown;
    GetCanonicalReleaseDate(): unknown;
    GetCanonicalReleaseYear(): unknown;
    GetGameID(): unknown;
    GetLastPlayedSectionName(): unknown;
    GetLastTimePlayed(): unknown;
    GetPerClientData(e: unknown): unknown;
    GetPrimaryAppID(): unknown;
    GetStoreTags(): unknown;
    InitFromProto(e: unknown): void;
    LOG_CHANGE(): unknown /* native code */;
    SetGameID(e: unknown): void;
    SetLastTimePlayed(e: unknown): void;
    SetPerClientData(e: unknown): void;
    SetSortAs(e: unknown): void;
    SetStoreCategories(e: unknown): void;
    SetStoreTags(e: unknown): void;
  
    __cachedLastPlayedSection: undefined;
    __cachedLastPlayedTime: undefined;
    __cachedReleaseYearString: undefined;
    active_beta: undefined;
    album_cover_hash: undefined;
    app_type: number;
    appid: number;
    canonicalAppType: number;
    display_name: string;
    display_status: number;
    gameid: string;
    gamepad_preferred: boolean;
    header_filename: string;
    icon_data: undefined;
    icon_data_format: undefined;
    icon_hash: string;
    installed: boolean;
    is_available_on_current_platform: boolean;
    is_invalid_os_type: undefined;
    library_capsule_filename: string;
    library_id: string;
    local_cache_version: number;
    local_per_client_data: Local_per_client_data2;
    m_gameid: undefined;
    m_setStoreCategories: Set<number>;
    m_setStoreTags: Set<number>;
    m_ulGameId: undefined;
    mastersub_appid: undefined;
    mastersub_includedwith_logo: undefined;
    metacritic_score: undefined;
    minutes_playtime_forever: number;
    minutes_playtime_last_two_weeks: number;
    most_available_clientid: string;
    most_available_per_client_data: Local_per_client_data2;
    mru_index: undefined;
    number_of_copies: number;
    optional_parent_app_id: undefined;
    owner_account_id: undefined;
    per_client_data: Local_per_client_data2[];
    ps4_controller_support: number;
    ps5_controller_support: number;
    review_percentage: number;
    review_percentage_with_bombs: number;
    review_percentage_without_bombs: number;
    review_score: number;
    review_score_with_bombs: number;
    review_score_without_bombs: number;
    rt_custom_image_mtime: undefined;
    rt_last_time_locally_played: undefined;
    rt_last_time_played: number;
    rt_last_time_played_or_installed: number;
    rt_original_release_date: number;
    rt_purchased_time: number;
    rt_recent_activity_time: number;
    rt_steam_release_date: number;
    rt_store_asset_mtime: number;
    selected_clientid: string;
    selected_per_client_data: Local_per_client_data2;
    shortcut_override_appid: undefined;
    site_license_site_name: undefined;
    size_on_disk: string;
    sort_as: string;
    status_percentage: number;
    steam_deck_compat_category: number;
    steam_hw_compat_category_packed: number;
    store_category: number[];
    store_tag: number[];
    subscribed_to: boolean;
    third_party_mod: undefined;
    visible_in_game_list: boolean;
    vr_only: undefined;
    vr_supported: undefined;
    xbox_controller_support: number;
  }
  
  export interface Collection14 {
    BAreCategoriesEqual(e: unknown): unknown;
    BAreSetsEqual(e: unknown, t: unknown): unknown;
    BAreStoreTagsEqual(e: unknown): unknown;
    BHasCustomImages(): boolean;
    BHasNonObservableChange(e: unknown): boolean;
    BHasObservableChange(e: unknown): boolean;
    BHasObservables(): boolean;
    BHasStoreCategory(e: unknown): unknown;
    BHasStoreTag(): unknown /* native code */;
    BIsAppBlocked(): unknown;
    BIsAppInBlockList(): unknown;
    BIsApplicationOrTool(): boolean;
    BIsBorrowed(): unknown;
    BIsDemo(): boolean;
    BIsGameIDEqual(e: unknown): boolean;
    BIsHardware(): boolean;
    BIsLastTimePlayedEqual(e: unknown): boolean;
    BIsModOrShortcut(): unknown;
    BIsMusicAlbum(): boolean;
    BIsNewToLibrary(): unknown;
    BIsOwned(): unknown;
    BIsOwnedByAnotherUser(): unknown;
    BIsPerClientDataEqual(e: unknown): boolean;
    BIsPerClientDataLocal(e: unknown): unknown;
    BIsSelectedClientLocal(): boolean;
    BIsShortcut(): boolean;
    BIsSortAsEqual(e: unknown): boolean;
    BIsSteamDeckVerified(): boolean;
    BIsSteamVR(): unknown;
    BIsUnreleased(): boolean;
    BIsVisibleInMRUList(): boolean;
    BSupportsVR(): unknown;
    ComputeLastPlayedSectionName(e: unknown): unknown;
    GetCanonicalReleaseDate(): unknown;
    GetCanonicalReleaseYear(): unknown;
    GetGameID(): unknown;
    GetLastPlayedSectionName(): unknown;
    GetLastTimePlayed(): unknown;
    GetPerClientData(e: unknown): unknown;
    GetPrimaryAppID(): unknown;
    GetStoreTags(): unknown;
    InitFromProto(e: unknown): void;
    LOG_CHANGE(): unknown /* native code */;
    SetGameID(e: unknown): void;
    SetLastTimePlayed(e: unknown): void;
    SetPerClientData(e: unknown): void;
    SetSortAs(e: unknown): void;
    SetStoreCategories(e: unknown): void;
    SetStoreTags(e: unknown): void;
  
    __cachedLastPlayedSection: undefined;
    __cachedLastPlayedTime: undefined;
    __cachedReleaseYearString: undefined;
    active_beta: undefined;
    album_cover_hash: undefined;
    app_type: number;
    appid: number;
    canonicalAppType: number;
    display_name: string;
    display_status: number;
    gameid: string;
    gamepad_preferred: boolean;
    header_filename: undefined;
    icon_data: undefined;
    icon_data_format: undefined;
    icon_hash: string;
    installed: undefined;
    is_available_on_current_platform: boolean;
    is_invalid_os_type: undefined;
    library_capsule_filename: string;
    library_id: undefined;
    local_cache_version: number;
    local_per_client_data: Local_per_client_data;
    m_gameid: undefined;
    m_setStoreCategories: Set<number>;
    m_setStoreTags: Set<number>;
    m_ulGameId: undefined;
    mastersub_appid: undefined;
    mastersub_includedwith_logo: undefined;
    metacritic_score: undefined;
    minutes_playtime_forever: number;
    minutes_playtime_last_two_weeks: number;
    most_available_clientid: string;
    most_available_per_client_data: Local_per_client_data;
    mru_index: undefined;
    number_of_copies: number;
    optional_parent_app_id: undefined;
    owner_account_id: undefined;
    per_client_data: Local_per_client_data[];
    ps4_controller_support: number;
    ps5_controller_support: number;
    review_percentage: number;
    review_percentage_with_bombs: number;
    review_percentage_without_bombs: number;
    review_score: number;
    review_score_with_bombs: number;
    review_score_without_bombs: number;
    rt_custom_image_mtime: number;
    rt_last_time_locally_played: undefined;
    rt_last_time_played: number;
    rt_last_time_played_or_installed: number;
    rt_original_release_date: number;
    rt_purchased_time: number;
    rt_recent_activity_time: number;
    rt_steam_release_date: number;
    rt_store_asset_mtime: number;
    selected_clientid: string;
    selected_per_client_data: Local_per_client_data;
    shortcut_override_appid: undefined;
    site_license_site_name: undefined;
    size_on_disk: undefined;
    sort_as: string;
    status_percentage: number;
    steam_deck_compat_category: number;
    steam_hw_compat_category_packed: number;
    store_category: number[];
    store_tag: number[];
    subscribed_to: boolean;
    third_party_mod: undefined;
    visible_in_game_list: boolean;
    vr_only: undefined;
    vr_supported: undefined;
    xbox_controller_support: number;
  }
  
  export interface Local_per_client_data {
    bytes_downloaded: string;
    bytes_total: string;
    client_name: string;
    clientid: string;
    display_status: number;
    is_available_on_current_platform: boolean;
    status_percentage: number;
  }
  
  export interface Local_per_client_data2 {
    bytes_downloaded: string;
    bytes_total: string;
    client_name: string;
    clientid: string;
    display_status: number;
    installed: boolean;
    is_available_on_current_platform: boolean;
    status_percentage: number;
  }
  
  export interface Local_per_client_data3 {
    active_beta: string;
    bytes_downloaded: string;
    bytes_total: string;
    client_name: string;
    clientid: string;
    display_status: number;
    installed: boolean;
    is_available_on_current_platform: boolean;
    status_percentage: number;
  }
  